# 1.	Write a Python Program to Add Two Matrices?

In [6]:
a = np.random.randint(1, 10, size=(3, 3))
b = np.random.randint(1, 10, size=(3, 3))

In [9]:
a

array([[7, 3, 2],
       [3, 3, 3],
       [9, 8, 6]])

In [10]:
b

array([[4, 8, 3],
       [6, 1, 8],
       [1, 8, 5]])

In [7]:
import numpy as np

def add_matrix(a, b):
    return a+b

In [8]:
add_matrix(a, b)

array([[11, 11,  5],
       [ 9,  4, 11],
       [10, 16, 11]])

# 2.	Write a Python Program to Multiply Two Matrices?

In [11]:
def matrix_multiplication(a, b):
    return a@b

In [12]:
matrix_multiplication(a, b)

array([[ 48,  75,  55],
       [ 33,  51,  48],
       [ 90, 128, 121]])

# 3.	Write a Python Program to Transpose a Matrix?

In [13]:
def transpose_matrix(a):
    return np.transpose(a)

In [14]:
transpose_matrix(a)

array([[7, 3, 9],
       [3, 3, 8],
       [2, 3, 6]])

# 4.	Write a Python Program to Sort Words in Alphabetic Order?

In [15]:
sentence = input("Enter the sentence: ")

words_list = sentence.split(" ")

words_list.sort()

for words in words_list:
    print(words, end=" ")


Enter the sentence: anees is artificial engineer
anees artificial engineer is 

# 5.	Write a Python Program to Remove Punctuation From a String?

In [16]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

new_string = ""

entered_string = input("Enter the sentence: ")

for char in entered_string:
    if char not in punctuations:
        new_string += char

print(new_string)

Enter the sentence: {Anees} is a <machine learning engineer>!!!!.
Anees is a machine learning engineer
