# 1.	Write a Python Program to Add Two Matrices?

In [259]:
import numpy as np

def add_matrix(a, b):
    return a+b

In [260]:
a = np.random.randint(1, 10, size=(3, 3))
b = np.random.randint(1, 10, size=(3, 3))

In [261]:
add_matrix(a, b)

array([[14,  7, 10],
       [15, 16, 13],
       [13, 12, 10]])

# 2.	Write a Python Program to Multiply Two Matrices?

In [266]:
def matrix_multiplication(a, b):
    return a@b

In [267]:
matrix_multiplication(a, b)

array([[121,  85,  94],
       [147, 107, 115],
       [130,  89,  99]])

# 3.	Write a Python Program to Transpose a Matrix?

In [23]:
def transpose_matrix(a):
    return np.transpose(a)

In [24]:
transpose_matrix(a)

array([[1, 3, 4],
       [6, 3, 3],
       [6, 3, 9]])

# 4.	Write a Python Program to Sort Words in Alphabetic Order?

In [258]:
sentence = input("Enter the sentence: ")

words_list = sentence.split(" ")

words_list.sort()

for words in words_list:
    print(words, end=" ")


Enter the sentence: anees is machine learning engineer
anees engineer is learning machine 

# 5.	Write a Python Program to Remove Punctuation From a String?

In [257]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

new_string = ""

entered_string = input("Enter the sentence: ")

for char in entered_string:
    if char not in punctuations:
        new_string += char

print(new_string)

Enter the sentence: {Anees} is a <machine learning engineer>!!!!.
Anees is a machine learning engineer
